import random
from abc import ABC, abstractmethod
from src.functions.poisson_sampling import poisson_sampling


class CenterPointsGenerator(ABC):
    """
    Class to generate and iterate over center points within a defined space.

    This abstract base class provides a framework for generating center points
    within a rectangular space defined by width and height. Subclasses must
    implement the `generate_points` method to define specific point generation
    logic. Once points are generated, an iterator is prepared to allow sequential
    access to the points.

    Attributes
    ----------
    size_x : int
        The width of the space where points are generated.
    size_y : int
        The height of the space where points are generated.
    number_of_points : int
        The total number of center points to be generated.
    """
    def __init__(self,
                 size_x:int,
                 size_y:int,
                 number_of_points:int):
        self.size_x = size_x
        self.size_y = size_y
        self.number_of_points = number_of_points
        self._points = []
        self._iterator = None

    @abstractmethod
    def generate_points(self) -> list:
        """
        This abstract method serves as a contract for subclasses to implement, ensuring
        a concrete mechanism is provided for generating a sequence of points. The
        method is expected to be overridden in subclasses to provide specific logic
        for generating and returning points as a list.

        Returns
        -------
        list
            A list of points generated by the implemented logic in the subclass.
        """
        pass

    def prepare_iterator(self):
        """
        Prepares and initializes the iterator for processing points.

        This method generates a set of points using the `generate_points` method
        and initializes an iterator over the generated points. A message is printed
        indicating the total number of points generated.

        Attributes
        ----------
        _points : list
            A private list of points generated by the `generate_points` method.
        _iterator : iterator
            A private iterator created from the list of points.

        See Also
        --------
        generate_points : Method used to create the list of points.

        Notes
        -----
        This is a preparatory method that must be called before attempting to
        iterate over the points. The method does not return any value but
        modifies the internal state of the object by initializing `_points` and
        `_iterator`.
        """
        self._points = self.generate_points()
        self._iterator = iter(self._points)
        print(f"Generated {len(self._points)} centers")

    def get_next_point(self):
        """
        Retrieves the next point from an iterator.

        This method checks whether the internal iterator is initialized and prepares it
        if needed. It retrieves the next point from the iterator, converts its coordinates
        to integers, and returns them as a tuple. If the iterator is exhausted, it returns None.

        Returns
        -------
        tuple of int or None
            A tuple containing the x and y coordinates as integers, or None if the iterator
            is exhausted.
        """
        if self._iterator is None:
            self.prepare_iterator()

        try:
            point = next(self._iterator)
            return int(point[0]), int(point[1])
        except StopIteration:
            return None

class PoissonAlgorithm(CenterPointsGenerator):
    """
    Summary of what the class does.

    The PoissonAlgorithm class is responsible for generating points on a 2D plane
    using the Poisson sampling algorithm. This class inherits from the
    CenterPointsGenerator class and enables users to specify the dimensions of the
    space, the minimum allowable distance between points, and other related parameters.

    Attributes
    ----------
    radius : int
        Minimum allowable distance between sampled points.
    k : int
        The number of candidate points to consider for each sample during the
        Poisson sampling process.
    """
    def __init__(self,
                 size_x:int,
                 size_y:int,
                 radius:int =5,
                 k:int =35):
        super().__init__(size_x,size_y,0)
        self.radius = radius
        self.k = k

    def generate_points(self):
        return poisson_sampling(self.size_x, self.size_y, self.radius, self.k)

class GaussianAlgorithm(CenterPointsGenerator):
    """
    Generates center points based on a Gaussian distribution.

    This class extends the functionality of the `CenterPointsGenerator` base class
    to generate a specified number of points within given dimensions. The points
    are distributed around the center of the specified area following a Gaussian
    distribution, controlled by a deviation factor.

    Attributes
    ----------
    size_x : int
        The width of the area in which points are generated.
    size_y : int
        The height of the area in which points are generated.
    number_of_points : int
        The total number of points to be generated.
    dev : int
        The deviation factor for the Gaussian distribution, affecting how spread out
        the points are around the central area.
    """
    def __init__(self,
                 size_x: int,
                 size_y: int,
                 number_of_points: int,
                 dev: int):
        super().__init__(size_x, size_y, number_of_points)
        self.dev = dev

    def generate_points(self):
        points = []
        center_x = self.size_x / 2
        center_y = self.size_y / 2

        for _ in range(self.number_of_points):
            x = random.gauss(center_x, self.dev)
            y = random.gauss(center_y, self.dev)

            x = max(0, min(int(x), self.size_x))
            y = max(0, min(int(y), self.size_y))

            points.append((int(x), int(y)))

        return points

class RandomAlignmentOfCenters(CenterPointsGenerator):
    """
    Generates random center points within given dimensions, ensuring alignment
    constraints based on cell size.

    This class is designed to create a specific number of random points within
    a defined width (`size_x`) and height (`size_y`) such that the points adhere
    to constraints related to the cell size. It inherits from the
    `CenterPointsGenerator` base class and adds specific functionality for
    centralized point alignment.

    Attributes
    ----------
    size_x : int
        Width of the area in which the random points will be generated.
    size_y : int
        Height of the area in which the random points will be generated.
    number_of_points : int
        Total number of random center points to generate.
    cell_size : int
        Defines the size of the constrained areas affecting the alignment
        of randomly generated points.
    """
    def __init__(self,
                 size_x: int,
                 size_y: int,
                 number_of_points: int,
                 cell_size: int):
        super().__init__(size_x, size_y, number_of_points )
        self.cell_size = cell_size

    def generate_points(self):
        points = []
        for _ in range(self.number_of_points):
            x = random.uniform(4 + self.cell_size, self.size_x - self.cell_size - 4)
            y = random.uniform(4 + self.cell_size, self.size_y - self.cell_size - 4)
            points.append((int(x), int(y)))

        return points


class ClusteredAlgorithm(CenterPointsGenerator):
    """
    Represents a clustered algorithm for generating points in a 2D space.

    This class generates a specified number of points clustered around randomly
    distributed centers within the 2D space. It inherits from the base
    `CenterPointsGenerator` class and enhances its functionality by introducing
    clusters with configurable deviation for point distribution.

    Attributes
    ----------
    num_clusters : int
        The number of clusters to generate within the 2D space. If not specified,
        a random value is assigned between 3 and 9 inclusive.
    dev : int
        The standard deviation determining the spread of points around each
        cluster center.
    """
    def __init__(self
                 , size_x: int
                 , size_y: int
                 , number_of_points: int
                 , num_clusters = None,
                 dev: int =40):
        super().__init__(size_x, size_y, number_of_points)
        self.num_clusters = num_clusters
        self.dev = dev

        if num_clusters is None:
            self.num_clusters = random.randint(3, 9)

    def generate_points(self):
        """
        Generates a set of random points within specified dimensions. Points are grouped
        around random cluster centers, with a degree of variation determined by a
        standard deviation.

        Returns
        -------
        list of tuple of int
            A list of 2D points represented as tuples of integers, where each tuple
            contains the x and y coordinates of a point. The generated points are
            bounded by the dimensions defined by `size_x` and `size_y`.
        """
        points = []

        cluster_centers = []
        for _ in range(self.num_clusters):
            cx = random.uniform(self.dev, self.size_x - self.dev)
            cy = random.uniform(self.dev, self.size_y - self.dev)
            cluster_centers.append((cx, cy))

        for _ in range(self.number_of_points):
            chosen_center = random.choice(cluster_centers)

            x = random.gauss(chosen_center[0], self.dev)
            y = random.gauss(chosen_center[1], self.dev)

            x = max(0, min(int(x), self.size_x))
            y = max(0, min(int(y), self.size_y))

            points.append((int(x), int(y)))

        return points